export const POST_PRODUCT = 'POST_PRODUCT';
export const GET_PRODUCTS_SELLER = 'GET_PRODUCTS_SELLER';

export const POST_PRODUCT_VISIBLE = 'POST_PRODUCT_VISIBLE';

export const PUT_PRODUCT = 'PUT_PRODUCT';

export const GET_SOLD = 'GET_SOLD'
export const GET_ALL_QUESTIONS = 'GET_ALL_QUESTIONS';


export const SELLER_INFO = 'SELLER_INFO'