export let POST_PRODUCT = 'POST_PRODUCT';
export let GET_PRODUCTS = 'GET_PRODUCTS';
export let GET_PRODUCTS_VISIBLE = 'GET_PRODUCTS_VISIBLE';
export let GET_PRODUCTS_NOVISIBLE = 'GET_PRODUCTS_NOVISIBLE';

export let POST_PRODUCT_VISIBLE = 'POST_PRODUCT_VISIBLE';

export let PUT_PRODUCT = 'PUT_PRODUCT';