// Buttons for Opening Login and Register
export const CHANGE_LOGIN = "CHANGE_LOGIN";
export const CHANGE_REGISTER = "CHANGE_REGISTER";

export const USER_DATA = "USER_DATA";

// Trying to connect to api to LOG IN
export const ATTEMPT_LOGIN = "ATTEMPT_LOGIN";
export const ATTEMPT_LOGIN_SUCCESS = "ATTEMPT_LOGIN_SUCCESS";
export const ATTEMPT_LOGIN_FAILED = "ATTEMPT_LOGIN_FAILED";
// Trying to connect to api to REGISTER
export const ATTEMPT_REGISTER = "ATTEMPT_REGISTER";
export const ATTEMPT_REGISTER_SUCCESS = "ATTEMPT_REGISTER_SUCCESS";
export const ATTEMPT_REGISTER_FAILED = "ATTEMPT_REGISTER_FAILED";

export const ATTEMPT_CONFIRM_ACCOUNT = "ATTEMPT_CONFIRM_ACCOUNT";

export const ATTEMPT_LOGOUT = "ATTEMPT_LOGOUT";

export const ATTEMPT_UPDATE_SUCCESS = 'ATTEMPT_UPDATE_SUCCESS'
export const ATTEMPT_UPDATE_FAILED = 'ATTEMPT_UPDATE_FAILED'

export const BECOME_SELLER = "BECOME_SELLER";
export const ATTEMPT_BECOME_SELLER = "ATTEMPT_BECOME_SELLER";
export const ATTEMPT_BECOME_SELLER_SUCCESS = "ATTEMPT_BECOME_SELLER_SUCCESS";
export const ATTEMPT_BECOME_SELLER_FAILED = "ATTEMPT_BECOME_SELLER_FAILED";