export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const GET_PRODUCTS_OFFER = 'GET_PRODUCTS_OFFER';
export const GET_CATEGORIES = 'GET_CATEGORIES';

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const POST_PRODUCT = 'POST_PRODUCT';
export const SORT = 'SORT';

export const GET_FAVOURITES = 'GET_FAVOURITES';

export const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS'

export const GET_PRODUCTS_INTERESTED = 'GET_PRODUCTS_INTERESTED'

export const GET_PRODUCTS_PCBUILDER = 'GET_PRODUCTS_PCBUILDER'
