export let GET_PRODUCTS = 'GET_PRODUCTS'
export let GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL'
export let GET_PRODUCTS_OFFER = 'GET_PRODUCTS_OFFER'
export let GET_CATEGORIES = 'GET_CATEGORIES'


export let UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export let POST_PRODUCT = 'POST_PRODUCT'
export let SORT = 'SORT'