let GET_CART = 'GET_CART'
let ADD_PRODUCT_CART = 'ADD_PRODUCT_CART'
let REMOVE_PRODUCT_CART = 'REMOVE_PRODUCT_CART'
let DECREMENT_PRODUCT_UNIT = 'DECREMENT_PRODUCT_UNIT'
let INCREMENT_PRODUCT_UNIT = 'INCREMENT_PRODUCT_UNIT'



let GET_PRODUCTS
let GET_PRODUCT_DETAIL
let UPDATE_PRODUCT
let POST_PRODUCT

let GET_SELLER_PRODUCTS
let GET_SELLER

let GET_USERS
let GET_USER_DETAIL
let UPDATE_USER

let GET_PRODUCT_CART
let POST_PRODUCT_CART
let GET_ALL_PRODUCTS_CART
