export let GET_CART = 'GET_CART'
export let ADD_PRODUCT_CART = 'ADD_PRODUCT_CART'
export let REMOVE_PRODUCT_CART = 'REMOVE_PRODUCT_CART'
export let DECREMENT_PRODUCT_UNIT = 'DECREMENT_PRODUCT_UNIT'
export let CHECKOUT = 'CHECKOUT'

