let GET_PRODUCTS
let GET_PRODUCT_DETAIL
let UPDATE_PRODUCT
let POST_PRODUCT

let GET_SELLER_PRODUCTS
let GET_SELLER

let GET_USERS
let GET_USER_DETAIL
let UPDATE_USER

let GET_PRODUCT_CART
let POST_PRODUCT_CART
let GET_ALL_PRODUCTS_CART
